name: Publish
on:
    push:
        tags:
            - v*.*.*
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js with npmjs
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org'
                  cache: 'npm'
            - name: Install NPM Packages
              run: npm ci
            - name: Run Tests
              run: npm test
            - name: Publish to npmjs
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            # - name: Setup Node.js with Github Packages
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: 20
            #       registry-url: 'https://npm.pkg.github.com'
            #       cache: 'npm'
            # - name: Publish to Github Packages
            #   run: npm publish
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
